### ISSUE TITLE
Unraid下运行镜像有问题

### ISSUE THREAD

**Issue by loveliveao** [lori255/base-yunzai-docker#1]
# lori你好，您编写的项目十分优秀，但是我在使用的时候出现了一些问题。
我使用的底层系统为unraid，如果想git TRSS-Yunzai会出错，而Miao-Yunzai不会。
docker run命令如下
```
docker run
  -d
  --name='base-yunzai'
  --net='eth1'
  --ip='10.0.1.111'
  --pids-limit 2048
  -e TZ="Asia/Shanghai"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Unraid-home"
  -e HOST_CONTAINERNAME="base-yunzai"
  -e 'YUNZAI_REPO_URL'='https://gitee.com/TimeRainStarSky/Yunzai'
  -l net.unraid.docker.managed=dockerman 'lori255/base-yunzai'
  --add-host=gitee.com:182.255.35.53
fb51f069db724c4a1f9c252dd61b8b2dc53ec4b8c0a52b8fe56932b9b0f7b3f7
```

在此情况下会报错，错误日志如下

```
Cloning into '/app/Yunzai'...
fatal: could not read Username for 'https://gitee.com': No such device or address
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
jq: error: Could not open file package.json: No such file or directory
 [信息]  拉取 Yunzai 更新  
 [提示]  检测到云崽目前没有安装，开始自动下载  
 [提示]  当前工作区有修改，尝试暂存后更新。
 [信息]  更新 Miao-Yunzai 运行依赖  
 ERR_PNPM_NO_PKG_MANIFEST  No package.json found in /app/Yunzai
```
您的项目能够持久化保存配置，十分优秀，已star！
如可以，请您百忙之中检查一下项目文件，谢谢！

**Comment by loveliveao** [comment]
现在如果使用QQ机器人，比较稳定的还是QQNT客户端通过ws连接到机器人框架，如果能直接git clone TRSS版的云崽确实很方便。我这边git clone喵崽之后还要输入node trss转到trss云崽，如果能直接git clone就完美了。

**Comment by loveliveao** [comment]
> 现在如果使用QQ机器人，比较稳定的还是QQNT客户端通过ws连接到机器人框架，如果能直接git clone TRSS版的云崽确实很方便。我这边git clone喵崽之后还要输入node trss转到trss云崽，如果能直接git clone就完美了。

刚刚试了一下,node trss会报错！只能通过Miao-Yunzai安装ws-plugin达到使用ws协议的目的，还在摸索中...

**Comment by lori255** [comment]
猜测可能是因为网络原因，或者添加gitee的host。现在trss已经支持使用docker安装了。
trss官方docker安装命令：bash <(curl -L https://gitee.com/TimeRainStarSky/Yunzai/raw/main/lib/tools/docker.sh)
详情见：https://gitee.com/TimeRainStarSky/Yunzai 下的docker安装

**Comment by loveliveao** [comment]
> 猜测可能是因为网络原因，或者添加gitee的host。现在trss已经支持使用docker安装了。 trss官方docker安装命令：bash <(curl -L https://gitee.com/TimeRainStarSky/Yunzai/raw/main/lib/tools/docker.sh) 详情见：https://gitee.com/TimeRainStarSky/Yunzai 下的docker安装

收到，猜测是我这边docker网络的问题，无法使用bridge网络进行pull，感谢回复！
